### ISSUE TITLE
sequencer64-kxstudio-ubuntu-14.04.5-LTS_0.93.3-0_amd64.deb segfaults on 17.04-kxstudio

### ISSUE THREAD

**Issue by hammerandtongs** [ahlstromcj/sequencer64-packages#3]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7de79c8 in call_init (l=<optimized out>, argc=1627421029, argc@entry=1, argv=argv@entry=0x7fffffffda08, 
    env=env@entry=0x7fffffffda18) at dl-init.c:72
72      dl-init.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7de79c8 in call_init (l=<optimized out>, argc=1627421029, 
    argc@entry=1, argv=argv@entry=0x7fffffffda08, env=env@entry=0x7fffffffda18) at dl-init.c:72
#1  0x00007ffff7de7adb in call_init (env=0x7fffffffda18, argv=0x7fffffffda08, argc=1, l=<optimized out>)
    at dl-init.c:30
#2  0x00007ffff7de7adb in _dl_init (main_map=0x7ffff7ffe168, argc=1, argv=0x7fffffffda08, env=0x7fffffffda18)
    at dl-init.c:120
#3  0x00007ffff7dd7c5a in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#4  0x0000000000000001 in  ()
#5  0x00007fffffffde11 in  ()
#6  0x0000000000000000 in  ()
(gdb)

**Comment by ahlstromcj** [comment]
That's a tough one?  Can you do an strace/ltrace and see what the last thing it was trying to do before it crapped out?  argc = a large number!

**Comment by hammerandtongs** [comment]
Weird, this was reproducible the other day but after reinstalling to strace it... working fine.

Sorry? Cheers.
