### ISSUE TITLE
2 Bugs with midi record

### ISSUE THREAD

**Issue by goguetchapuisb** [ahlstromcj/sequencer64-packages#5]
Hello,
Sometimes, I've 2 bugs with the midi record : 
The first one is the first beat wouldn't recorded on the grid
The second one is the press time is not recorded
![bug seq64](https://user-images.githubusercontent.com/33229430/32252265-ef7b3e6a-be94-11e7-9123-93022ce35e15.png)
maybe i've not a good configuration.
I'm beginning with seq64
I've a good feeling with this application but this bugs are so bad...
Thanks for your works

**Comment by ahlstromcj** [comment]
It's pretty difficult to get the Note On right at the beginning of the pattern, but it does work.  I can also record long notes, but on a long pattern.  I did notice a couple odd drawing artefacts I need to look into, though.  Have patience, my friend!
