### ISSUE TITLE
Display Bug

### ISSUE THREAD

**Issue by goguetchapuisb** [ahlstromcj/sequencer64-packages#6]
Hello,

Sometimes I have a very strange display bug, the screen freezes and applications disappear in part. They can reappear on mouse over. Everything goes in order when I leave seq64 ...
I'me in dual screen mode and I have the impression that this happens when I pass seq64 of the first screen to the second. But it's not every time...

**Comment by ahlstromcj** [comment]
I'll check it out, but it's probably due to a shared library on your system being incompatible with what seq64 was built against.  At some point I will work on a static build to avoid this issue.
