### ISSUE TITLE
BPM Jack Transport

### ISSUE THREAD

**Issue by goguetchapuisb** [ahlstromcj/sequencer64-packages#7]
Hello,

With Jack Transport, BPM in seq 64 don't works. When it is in slave mode, BPM  is not modified by the master and when it is in master mode, it don't modify the slave.

Thanks

**Comment by ahlstromcj** [comment]
This is fixed in 0.90.6 (in the source-code project https://github.com/ahlstromcj/sequencer64.  At some point I will update the package here, and probably also try to make a static build.
